image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - cd backend
  - chmod +x ./gradlew

build:
  stage: build
  script:
    - ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  dependencies:
    - build
  script:
    - ./gradlew test
    - cat build/jacocoHtml/index.html
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    when: always
    paths:
      - build/test-results/test/
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
