stages:
  - test

test:
  stage: test
  script:
    - gradle clean test
  artifacts:
    when: always
    paths:
      - backend/build/reports/jacoco/test/
    reports:
      junit:
        - jacocoTestReport.xml