server:
  port: 8082
  servlet:
    session:
      cookie:
        max-age: 172800
      timeout: 86400

spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
